export { default as banners } from "./banners";
export { default as featured } from "./featured";
export { default as sponsers } from "./sponsers";
export { default as blogs } from "./blogs";
export { default as products } from "./special-products";
export { default as categories } from "./categories";
export { default as mobiles } from "./mobiles";
export { default as hero_banners } from "./hero-banners";
export { default as compare_products } from "./compare-products";
